#!/bin/sh

. /etc/profile.d/oracle-oci8.sh

[ -e /lib64 ] || [ "$(uname -m)" != "x86_64" ] || ln -s /lib /lib64

grep -q "^oracle-oci8" "/etc/ld.so.conf" || echo "/usr/local/oracle-oci8" >> /etc/ld.so.conf
ldconfig -q
